project_id = "fontsvmexlkwqgbfrwtl"

[functions.transcribe-audio]
verify_jwt = true

[functions.summarize-note]
verify_jwt = true

[functions.realtime-transcribe]
verify_jwt = false

[functions.generate-title]
verify_jwt = true